//TokenType.java
enum TokenType{
    
    // Literals
    NUMBER, STRING, IDENTIFIER, AFFIRMATIVE, DENIED,

    // Keywords
    AGENT, INTEL, VERIFY, ALTERNATIVE, OTHERWISE , INFILTRATE, PENETRATE,
    PROTOCOL, RULE, DEFAULT, ABORT, PROCEED, MISSION, OPERATION, EXTRACT,

    // Logic
    AND, OR, NOT,

    // Symbols
    PLUS, MINUS, STAR, SLASH, PERCENT,
    LPAREN, RPAREN, LBRACES, RBRACES,
    COMMA, SEMI_COLON, COLON, EQUAL, 
    EQUAL_EQUAL, BANG_EQUAL,
    LESS, GREATER, LESS_EQUAL, GREATER_EQUAL,
    PLUS_PLUS, MINUS_MINUS, DOT,

    EOF

}